### ISSUE TITLE
How wait new message from user?

### ISSUE THREAD

**Issue by Radzhab** [xakpc/TelegramBot.Client#1]
How wait new message from user? Ex. i have algorithm. 

```
if (text == "/weather")
                    {
                       bot.sendText("please type city");
                       var rezult = WaitNewMessage();
                     }
```

**Comment by xakpc** [comment]
You can get user messages by getUpdates method (will pull all new messages) or via webhook
For more info refer to official docs
https://core.telegram.org/bots/api#getting-updates
