### ISSUE TITLE
How to set thumbnail when using sendvideo method

### ISSUE THREAD

**Issue by Mohammad-Saheb** [xakpc/TelegramBot.Client#2]
Hi
How can I set thumbnail when using SendVideoAsync method ?

var message = await apiClient.SendVideoAsync(TestChatId, new InputFile(Resources.video, "video.mp4"), 572, "Linus Torvalds says GPL v3 violates everything that GPLv2 stood for", null, null);

http://oi60.tinypic.com/33ml5pj.jpg

Also message.video.thumb is null !!?

Thanks .

**Comment by xakpc** [comment]
I do not see any way to set thumbnail in Telegram Api. Returned message.video.thumb is generated from sent video i assume.
